import "server-only";
import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { del, put } from "@vercel/blob";

/**
 * Minimal file storage: local disk in development, Vercel Blob in production (Vercel has
 * no persistent disk). Selected by the presence of BLOB_READ_WRITE_TOKEN.
 *
 * `save` returns a URL the browser can load directly.
 */
export type StoredFile = { url: string; key: string };

const LOCAL_ROOT = path.join(process.cwd(), "uploads");
const blobEnabled = () => Boolean(process.env.BLOB_READ_WRITE_TOKEN);

export async function saveFile(key: string, data: Buffer, contentType: string): Promise<StoredFile> {
  assertSafeKey(key);
  if (blobEnabled()) {
    const blob = await put(key, data, { access: "public", contentType, addRandomSuffix: false, allowOverwrite: true });
    return { url: blob.url, key };
  }
  const file = path.join(LOCAL_ROOT, key);
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, data);
  return { url: `/api/files/${key}`, key };
}

export async function deleteFile(urlOrKey: string): Promise<void> {
  try {
    if (blobEnabled()) {
      await del(urlOrKey);
    } else {
      const key = urlOrKey.replace(/^\/api\/files\//, "");
      assertSafeKey(key);
      await unlink(path.join(LOCAL_ROOT, key));
    }
  } catch {
    // Already gone; deleting an old photo is best-effort.
  }
}

/** Local development only: read a file saved by saveFile. */
export async function readLocalFile(key: string): Promise<Buffer | null> {
  assertSafeKey(key);
  try {
    return await readFile(path.join(LOCAL_ROOT, key));
  } catch {
    return null;
  }
}

// Keys are generated by us, but be strict anyway: no traversal, no absolute paths.
function assertSafeKey(key: string) {
  if (!/^[a-z0-9][a-z0-9/_.-]*$/i.test(key) || key.includes("..")) {
    throw new Error(`Unsafe storage key: ${key}`);
  }
}
